services:
  web:
    image: ''
    restart: always
    ports:
      - "3000:3000"
    volumes:
     - .:/app
     - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3000/api
    stdin_open: true
    tty: true
    command: npm start